carla_host: localhost
carla_port: 2000
# 可填真实 CARLA PythonAPI 目录，或课程提供的 fake carla.py 所在目录/文件路径
carla_pythonapi_path: "../../hutb/PythonAPI/carla/dist"
vehicle_blueprint: vehicle.lincoln.mkz_2017

simulation:
  width: 800
  height: 600
  fps: 30

controller:
  kp: 0.8
  ki: 0.0
  kd: 0.1
  max_steering_angle: 45
  default_throttle: 0.3

vision:
  canny_thresh1: 50
  canny_thresh2: 150
